language: node_js
node_js:
    - '8'
cache:
    directories:
        - 'node_modules'
script: yarn test && codecov && yarn storybook:export
deploy:
    skip-cleanup: true
    provider: surge
    project: build
    domain: react-scroll-parallax-next.surge.sh
    on: next
